"""
Django settings for site_django project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  #СОДЕРЖИТ ПОЛНЫЙ ПУТЬ К ПАПКЕ ПРОЕКТАЫ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d-f)pe^cia1z626lw+_qpi^7#-nof3h)a$t9q^0y5ed25#!60&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #ЧТОБЫ ВСЕ ОШИБКИ ОТОБРАЖАЛСЬ В БРАУЗЕРЕ, False - НАОБОРОТ
# ПЕРЕД ВЫГРУЗКОЙ НА ХОСТИНГ СТАВИМ False

ALLOWED_HOSTS = [] #СПИСОК РАЗРЕШЕННЫХ ХОСТОВ


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'users.apps.UsersConfig'
]  #СЮДА ЗАПИСЫВАЮТСЯ ПРИЛОЖЕНИЯ, КОТОРЫЕ НЕОБХОДИМЫ НАМ ДЛЯ РАБОТЫ

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}  #ЗДЕСЬ УКАЗЫВАЕМ БАЗУ ДАННЫХ, С КОТОРОЙ БУДЕМ РАБОТАТЬ


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru' #ЯЗЫК САЙТА

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# для отправки писем на почту (работает только на удаленном сервере, на локальном - не факт)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'logomail29@gmail.com' #прописываем от кого происходит отправка письма
EMAIL_HOST_PASSWORD = 'nmnqgeooslpjmnym' #для авторизации почты


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'   #РАСПОЛОЖЕНИЕ СТАТИЧЕСКИХ ФАЙЛОВ(CSS HTML И Т.Д.)

STATICFILES_DIRS = [
    BASE_DIR / "static"
]  # нужно прописывать такой список для статическихфайлов - css, img и т.д. Удалить второй элемент

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'profile' # куда мы будем переадресовывать пользователя после авторизации

LOGIN_URL = 'user' #указываем, куда будет перебрасывать пользователя, если он попытается попасть на страницу только для авторизованных пользователей

MEDIA_URL = '/pictures/' #указываем, откуда будут браться картинки

MEDIA_ROOT = os.path.join(BASE_DIR, 'pictures') # соединяем общий путь к проекту(BASE_DIR) и папку для фото
                                                # чтобы фото корректно подгружались куда нужно
